export type Range = [number, number]

export const colors = {
  blue: '#3388ff',
  orange: '#ffa500',
}

export const controlTitles = {
  priority: 'Priority Pixels',
  feasibility: 'Feasibility Pixels',
}

export const initialScoreRanges: Record<string, Range> = {
  // popRange: [0, 0],
  cjScoreRange: [0, 100],
  // ejScoreRange: [0, 0],
  ciScoreRange: [0, 100],
  levRange: [0, 1000],
  multiFaRange: [0, 100],
  rentersRange: [0, 100],
  walkableRange: [0, 100],
  drivableRange: [0, 100],
  // commercialRange: [0, 0],
  // residentialRange: [0, 0],
  nonWhiteRange: [0, 100],
  commuteRange: [0, 100],
  disabilityRange: [0, 100],
  pgeRange: [0, 3000],
  // CES SubIndicators
  cesOzoneRange: [0, 100],
  cesPm25Range: [0, 100],
  cesDieselPmRange: [0, 100],
  cesTrafficRange: [0, 100],
  cesAsthmaRange: [0, 100],
  cesLowBirthWeightRange: [0, 100],
  cesCardiovascularDiseaseRange: [0, 100],
  cesEducationRange: [0, 100],
  cesLinguisticIsolationRange: [0, 100],
  cesPovertyRange: [0, 100],
  cesUnemploymentRange: [0, 100],
  cesHousingBurdenRange: [0, 100],
  // EJScreen SubIndicators
  ejscreenOzoneRange: [0, 100],
  ejscreenPm25Range: [0, 100],
  ejscreenDieselPmRange: [0, 100],
  ejscreenRseiAirRange: [0, 100],
  ejscreenPtrafRange: [0, 100],
  ejscreenNo2Range: [0, 100],
  // CJEST SubIndicators
  cjestDieselExRange: [0, 100],
  cjestPm25Range: [0, 100],
  cjestTrafficRange: [0, 100],
  cjestLowLifeExRange: [0, 100],
  cjestAsthmaRange: [0, 100],
  cjestHeartDisRange: [0, 100],
  cjestHouseBurdRange: [0, 100],
  cjestLingIsoRange: [0, 100],
  cjestEducationRange: [0, 100],
  cjestLmiRange: [0, 100],
  cjestFpl100Range: [0, 100],
  cjestFpl200Range: [0, 100],
  cjestUnemploymentRange: [0, 100],
}

export const maxValues = {
  popMax: 200,
  ciScoreMax: 100,
  cjScoreMax: 100,
  ejScoreMax: 100,
  levMax: 1000,
  multiFaMax: 100,
  rentersMax: 100,
  walkableMax: 100,
  drivableMax: 100,
  commercialMax: 100,
  residentialMax: 100,
  nonWhiteMax: 100,
  commuteMax: 100,
  disabilityMax: 100,
  pgeMax: 3000,
  // CES SubIndicators
  cesOzoneMax: 100,
  cesPm25Max: 100,
  cesDieselPmMax: 100,
  cesTrafficMax: 100,
  cesAsthmaMax: 100,
  cesLowBirthWeightMax: 100,
  cesCardiovascularDiseaseMax: 100,
  cesEducationMax: 100,
  cesLinguisticIsolationMax: 100,
  cesPovertyMax: 100,
  cesUnemploymentMax: 100,
  cesHousingBurdenMax: 100,
  // EJScreen SubIndicators
  ejscreenOzoneMax: 100,
  ejscreenPm25Max: 100,
  ejscreenDieselPmMax: 100,
  ejscreenRseiAirMax: 100,
  ejscreenPtrafMax: 100,
  ejscreenNo2Max: 100,
  // CJEST SubIndicators
  cjestDieselExMax: 100,
  cjestPm25Max: 100,
  cjestTrafficMax: 100,
  cjestLowLifeExMax: 100,
  cjestAsthmaMax: 100,
  cjestHeartDisMax: 100,
  cjestHouseBurdMax: 100,
  cjestLingIsoMax: 100,
  cjestEducationMax: 100,
  cjestLmiMax: 100,
  cjestFpl100Max: 100,
  cjestFpl200Max: 100,
  cjestUnemploymentMax: 100,
}

export const configIndicatorLabels = {
  toggleCesOzoneRange: 'Ozone Pollution',
  toggleCesPm25Range: 'PM2.5 Pollution',
  toggleCesDieselPmRange: 'Diesel Particulate Matter',
  toggleCesTrafficRange: 'Traffic Density',
  toggleCesAsthmaRange: 'Asthma Prevalence',
  toggleCesLowBirthWeightRange: 'Low Birth Weight',
  toggleCesCardiovascularDiseaseRange: 'Cardiovascular Disease',
  toggleCesEducationRange: 'Educational Attainment',
  toggleCesLinguisticIsolationRange: 'Linguistic Isolation',
  toggleCesPovertyRange: 'Poverty Rate',
  toggleCesUnemploymentRange: 'Unemployment Rate',
  toggleCesHousingBurdenRange: 'Housing Cost Burden',
  toggleEjScreenOzoneRange: 'Ozone Pollution',
  toggleEjScreenPm25Range: 'PM2.5 Pollution',
  toggleEjScreenDieselPmRange: 'Diesel Particulate Matter',
  toggleEjScreenRseiAirRange: 'Toxic Air Releases (RSEI)',
  toggleEjScreenPtrafRange: 'Proximity to Traffic',
  toggleEjScreenNo2Range: 'Nitrogen Dioxide (NO₂) Pollution',
  toggleCjestDieselExRange: 'Diesel Exposure',
  toggleCjestPm25Range: 'PM2.5 Pollution',
  toggleCjestTrafficRange: 'Traffic Density',
  toggleCjestLowLifeExRange: 'Low Life Expectancy',
  toggleCjestAsthmaRange: 'Asthma Prevalence',
  toggleCjestHeartDisRange: 'Heart Disease Risk',
  toggleCjestHouseBurdRange: 'Housing Burden',
  toggleCjestLingIsoRange: 'Linguistic Isolation',
  toggleCjestEducationRange: 'Educational Attainment',
  toggleCjestLmiRange: 'Low-Moderate Income',
  toggleCjestFpl100Range: 'Below 100% FPL',
  toggleCjestFpl200Range: 'Below 200% FPL',
  toggleCjestUnemploymentRange: 'Unemployment Rate',
  toggleNonWhiteRange: 'Non-white %',
  toggleCommuteRange: 'Commute Distance %',
  toggleDisabilityRange: 'Disability %',
}

export const polygonIndicatorLabels: { [key: string]: string } = {
  pop: 'Population (total)',
  chg_walk_L2_10: 'L2 chargers w/in 10min walk',
  chg_drive_DCF_10: 'DC chargers w/in 10min drive',
  CIscoreP: 'CalEnviroScreen composite',
  OzoneP: 'CES Ozone %ile',
  DieselPM_P: 'CES Diesel PM %ile',
  PM2_5_P: 'CES PM2.5 %ile',
  TrafficP: 'CES traffic %ile',
  AsthmaP: 'CES asthma emerg. visits %ile',
  LowBirWP: 'CES low birth weight %ile',
  CardiovasP: 'CES cardiovascular disease %ile',
  EducatP: 'CES < HS education %ile',
  Ling_IsolP: 'CES Linguistic isolation %ile',
  PovertyP: 'CES poverty %ile',
  UnemplP: 'CES unemployment %ile',
  HousBurdP: 'CES housing burden %ile',
  PopCharP: 'Population characteristics %',
  P_D2_PM25: 'EJScreen PM2.5 %ile',
  P_D2_OZONE: 'EJScreen Ozone %ile',
  P_D2_DSLPM: 'EJScreen Diesel PM %ile',
  P_D2_RSEI_AIR: 'EJScreen Toxic Releases to Air %ile',
  P_D2_PTRAF: 'EJScreen Traffic Proximity %ile',
  P_D2_NO2: 'EJScreen NO2 %ile',
  disadvantaged: 'Disadvantaged %ile',
  diesel_ex: 'CJEST diesel PM %ile',
  pm25: 'CJEST PM2.5 %ile',
  traffic: 'CJEST traffic %ile',
  low_life_ex: 'Low-life expectancy %ile',
  heart_dis: 'CJEST cardiovascular disease %ile',
  house_burd: 'CJEST Housing burden %ile',
  ling_iso: 'CJEST linguistic isolation %ile',
  education: 'CJEST < HS education %ile',
  LMI: 'Low-Moderate Income %ile',
  '100_fpl': 'Below 100% FPL',
  '200_fpl': 'Below 200% FPL',
  unemployment: 'CJEST u  nemployment %',
  non_white_pctl: 'Census nonwhite %',
  commute_pctl: 'Census commute distance %ile',
  disability_pctl: 'Census disability %',
  'Multi-Family Housing Residents': 'MFH residents',
  Renters: 'Renters',
  lev_10000: 'Registered LEVs',
  pge: 'Grid capacity (kW)',
  nevi: 'NEVI program',
  irs30c: '30c property tax credit',
}

// export const conditions = {
//   toggleCiRange: {
//       value: props.CIscoreP,
//       range: ciScoreRange,
//       max: ciScoreMax,
//   },
//   toggleCJESTRange: {
//       value: props.disadvantaged,
//       range: cjScoreRange,
//       max: cjScoreMax,
//   },
//   toggleMultiFaRange: {
//       value: props['Multi-Family Housing Residents'],
//       range: multiFaRange,
//       max: multiFaMax,
//   },
//   toggleRentersRange: {
//       value: props.Renters,
//       range: rentersRange,
//       max: rentersMax,
//   },
//   toggleWalkableRange: {
//       value: chg_walk,
//       range: walkableRange,
//       max: walkableMax,
//   },
//   toggleDrivableRange: {
//       value: chg_drive,
//       range: drivableRange,
//       max: drivableMax,
//   },
//   toggleLevRange: {
//       value: props.lev_10000,
//       range: levRange,
//       max: levMax,
//   },
//   togglePgeRange: {
//       value: pgeOrUtility,
//       range: pgeRange,
//       max: pgeMax,
//   },
//   toggleCesOzoneRange: {
//       value: props.OzoneP,
//       range: cesOzoneRange,
//       max: cesOzoneMax,
//   },
//   toggleCesPm25Range: {
//       value: props.DieselPM_P,
//       range: cesPm25Range,
//       max: cesPm25Max,
//   },
//   toggleCesDieselPmRange: {
//       value: props.PM2_5_P,
//       range: cesDieselPmRange,
//       max: cesDieselPmMax,
//   },
//   toggleCesTrafficRange: {
//       value: props.TrafficP,
//       range: cesTrafficRange,
//       max: cesTrafficMax,
//   },
//   toggleCesAsthmaRange: {
//       value: props.AsthmaP,
//       range: cesAsthmaRange,
//       max: cesAsthmaMax,
//   },
//   toggleCesLowBirthWeightRange: {
//       value: props.LowBirWP,
//       range: cesLowBirthWeightRange,
//       max: cesLowBirthWeightMax,
//   },
//   toggleCesCardiovascularDiseaseRange: {
//       value: props.CardiovasP,
//       range: cesCardiovascularDiseaseRange,
//       max: cesCardiovascularDiseaseMax,
//   },
//   toggleCesEducationRange: {
//       value: props.EducatP,
//       range: cesEducationRange,
//       max: cesEducationMax,
//   },
//   toggleCesLinguisticIsolationRange: {
//       value: props.Ling_IsolP,
//       range: cesLinguisticIsolationRange,
//       max: cesLinguisticIsolationMax,
//   },
//   toggleCesPovertyRange: {
//       value: props.PovertyP,
//       range: cesPovertyRange,
//       max: cesPovertyMax,
//   },
//   toggleCesUnemploymentRange: {
//       value: props.UnemplP,
//       range: cesUnemploymentRange,
//       max: cesUnemploymentMax,
//   },
//   toggleCesHousingBurdenRange: {
//       value: props.HousBurdP,
//       range: cesHousingBurdenRange,
//       max: cesHousingBurdenMax,
//   },
//   toggleEjScreenOzoneRange: {
//       value: props.P_D2_OZONE,
//       range: ejscreenOzoneRange,
//       max: ejscreenOzoneMax,
//   },
//   toggleEjScreenPm25Range: {
//       value: props.P_D2_PM25,
//       range: ejscreenPm25Range,
//       max: ejscreenPm25Max,
//   },
//   toggleEjScreenDieselPmRange: {
//       value: props.P_D2_DSLPM,
//       range: ejscreenDieselPmRange,
//       max: ejscreenDieselPmMax,
//   },
//   toggleEjScreenRseiAirRange: {
//       value: props.P_D2_RSEI_AIR,
//       range: ejscreenRseiAirRange,
//       max: ejscreenRseiAirMax,
//   },
//   toggleEjScreenPtrafRange: {
//       value: props.P_D2_PTRAF,
//       range: ejscreenPtrafRange,
//       max: ejscreenPtrafMax,
//   },
//   toggleEjScreenNo2Range: {
//       value: props.P_D2_NO2,
//       range: ejscreenNo2Range,
//       max: ejscreenNo2Max,
//   },
//   toggleCjestDieselExRange: {
//       value: props.diesel_ex,
//       range: cjestDieselExRange,
//       max: cjestDieselExMax,
//   },
//   toggleCjestPm25Range: {
//       value: props.pm25,
//       range: cjestPm25Range,
//       max: cjestPm25Max,
//   },
//   toggleCjestTrafficRange: {
//       value: props.traffic,
//       range: cjestTrafficRange,
//       max: cjestTrafficMax,
//   },
//   toggleCjestLowLifeExRange: {
//       value: props.low_life_ex,
//       range: cjestLowLifeExRange,
//       max: cjestLowLifeExMax,
//   },
//   // toggleCjestAsthmaRange: { value: pgeOrUtility, range: cjestAsthmaRange, max: cjestAsthmaMax },
//   toggleCjestHeartDisRange: {
//       value: props.heart_dis,
//       range: cjestHeartDisRange,
//       max: cjestHeartDisMax,
//   },
//   toggleCjestHouseBurdRange: {
//       value: props.house_burd,
//       range: cjestHouseBurdRange,
//       max: cjestHouseBurdMax,
//   },
//   toggleCjestLingIsoRange: {
//       value: props.ling_iso,
//       range: cjestLingIsoRange,
//       max: cjestLingIsoMax,
//   },
//   toggleCjestEducationRange: {
//       value: props.education,
//       range: cjestEducationRange,
//       max: cjestEducationMax,
//   },
//   toggleCjestLmiRange: {
//       value: props.LMI,
//       range: cjestLmiRange,
//       max: cjestLmiMax,
//   },
//   toggleCjestFpl100Range: {
//       value: props['100_fpl'],
//       range: cjestFpl100Range,
//       max: cjestFpl100Max,
//   },
//   toggleCjestFpl200Range: {
//       value: props['200_fpl'],
//       range: cjestFpl200Range,
//       max: cjestFpl200Max,
//   },
//   toggleCjestUnemploymentRange: {
//       value: props.unemployment,
//       range: cjestUnemploymentRange,
//       max: cjestUnemploymentMax,
//   },
// }
