export type Range = [number, number]

export const colors = {
  blue: '#3388ff',
  orange: '#ffa500',
}

export const controlTitles = {
  priority: 'Priority Pixels',
  feasibility: 'Feasibility Pixels',
}

export const initialScoreRanges: Record<string, Range> = {
  // popRange: [0, 0],
  cjScoreRange: [0, 100],
  // ejScoreRange: [0, 0],
  ciScoreRange: [0, 100],
  levRange: [0, 1000],
  multiFaRange: [0, 100],
  rentersRange: [0, 100],
  walkableRange: [0, 100],
  drivableRange: [0, 100],
  // commercialRange: [0, 0],
  // residentialRange: [0, 0],
  nonWhiteRange: [0, 100],
  commuteRange: [0, 100],
  disabilityRange: [0, 100],
  pgeRange: [0, 3000],
  // CES SubIndicators
  cesOzoneRange: [0, 100],
  cesPm25Range: [0, 100],
  cesDieselPmRange: [0, 100],
  cesTrafficRange: [0, 100],
  cesAsthmaRange: [0, 100],
  cesLowBirthWeightRange: [0, 100],
  cesCardiovascularDiseaseRange: [0, 100],
  cesEducationRange: [0, 100],
  cesLinguisticIsolationRange: [0, 100],
  cesPovertyRange: [0, 100],
  cesUnemploymentRange: [0, 100],
  cesHousingBurdenRange: [0, 100],
  // EJScreen SubIndicators
  ejscreenOzoneRange: [0, 100],
  ejscreenPm25Range: [0, 100],
  ejscreenDieselPmRange: [0, 100],
  ejscreenRseiAirRange: [0, 100],
  ejscreenPtrafRange: [0, 100],
  ejscreenNo2Range: [0, 100],
  // CEJST SubIndicators
  cejstDieselExRange: [0, 100],
  cejstPm25Range: [0, 100],
  cejstTrafficRange: [0, 100],
  cejstLowLifeExRange: [0, 100],
  cejstAsthmaRange: [0, 100],
  cejstHeartDisRange: [0, 100],
  cejstHouseBurdRange: [0, 100],
  cejstLingIsoRange: [0, 100],
  cejstEducationRange: [0, 100],
  cejstLmiRange: [0, 100],
  cejstFpl100Range: [0, 100],
  cejstFpl200Range: [0, 100],
  cejstUnemploymentRange: [0, 100],
}

export const maxValues = {
  popMax: 200,
  ciScoreMax: 100,
  cjScoreMax: 100,
  ejScoreMax: 100,
  levMax: 1000,
  multiFaMax: 100,
  rentersMax: 100,
  walkableMax: 100,
  drivableMax: 100,
  commercialMax: 100,
  residentialMax: 100,
  nonWhiteMax: 100,
  commuteMax: 100,
  disabilityMax: 100,
  pgeMax: 3000,
  // CES SubIndicators
  cesOzoneMax: 100,
  cesPm25Max: 100,
  cesDieselPmMax: 100,
  cesTrafficMax: 100,
  cesAsthmaMax: 100,
  cesLowBirthWeightMax: 100,
  cesCardiovascularDiseaseMax: 100,
  cesEducationMax: 100,
  cesLinguisticIsolationMax: 100,
  cesPovertyMax: 100,
  cesUnemploymentMax: 100,
  cesHousingBurdenMax: 100,
  // EJScreen SubIndicators
  ejscreenOzoneMax: 100,
  ejscreenPm25Max: 100,
  ejscreenDieselPmMax: 100,
  ejscreenRseiAirMax: 100,
  ejscreenPtrafMax: 100,
  ejscreenNo2Max: 100,
  // CEJST SubIndicators
  cejstDieselExMax: 100,
  cejstPm25Max: 100,
  cejstTrafficMax: 100,
  cejstLowLifeExMax: 100,
  cejstAsthmaMax: 100,
  cejstHeartDisMax: 100,
  cejstHouseBurdMax: 100,
  cejstLingIsoMax: 100,
  cejstEducationMax: 100,
  cejstLmiMax: 100,
  cejstFpl100Max: 100,
  cejstFpl200Max: 100,
  cejstUnemploymentMax: 100,
}

export const configIndicatorLabels = {
  toggleCesOzoneRange: 'Ozone Pollution',
  toggleCesPm25Range: 'PM2.5 Pollution',
  toggleCesDieselPmRange: 'Diesel Particulate Matter',
  toggleCesTrafficRange: 'Traffic Density',
  toggleCesAsthmaRange: 'Asthma Prevalence',
  toggleCesLowBirthWeightRange: 'Low Birth Weight',
  toggleCesCardiovascularDiseaseRange: 'Cardiovascular Disease',
  toggleCesEducationRange: 'Educational Attainment',
  toggleCesLinguisticIsolationRange: 'Linguistic Isolation',
  toggleCesPovertyRange: 'Poverty Rate',
  toggleCesUnemploymentRange: 'Unemployment Rate',
  toggleCesHousingBurdenRange: 'Housing Cost Burden',
  toggleEjScreenOzoneRange: 'Ozone Pollution',
  toggleEjScreenPm25Range: 'PM2.5 Pollution',
  toggleEjScreenDieselPmRange: 'Diesel Particulate Matter',
  toggleEjScreenRseiAirRange: 'Toxic Air Releases (RSEI)',
  toggleEjScreenPtrafRange: 'Proximity to Traffic',
  toggleEjScreenNo2Range: 'Nitrogen Dioxide (NO₂) Pollution',
  toggleCejstDieselExRange: 'Diesel Exposure',
  toggleCejstPm25Range: 'PM2.5 Pollution',
  toggleCejstTrafficRange: 'Traffic Density',
  toggleCejstLowLifeExRange: 'Low Life Expectancy',
  toggleCejstAsthmaRange: 'Asthma Prevalence',
  toggleCejstHeartDisRange: 'Heart Disease Risk',
  toggleCejstHouseBurdRange: 'Housing Burden',
  toggleCejstLingIsoRange: 'Linguistic Isolation',
  toggleCejstEducationRange: 'Educational Attainment',
  toggleCejstLmiRange: 'Low-Moderate Income',
  toggleCejstFpl100Range: 'Below 100% FPL',
  toggleCejstFpl200Range: 'Below 200% FPL',
  toggleCejstUnemploymentRange: 'Unemployment Rate',
  toggleNonWhiteRange: 'Non-white %',
  toggleCommuteRange: 'Commute Distance %',
  toggleDisabilityRange: 'Disability %',
}

export const polygonIndicatorLabels: { [key: string]: string } = {
  pop: 'Population (total)',
  chg_walk_L2_10: 'L2 chargers w/in 10min walk',
  chg_drive_DCF_10: 'DC chargers w/in 10min drive',
  CIscoreP: 'CalEnviroScreen composite',
  OzoneP: 'CES Ozone %ile',
  DieselPM_P: 'CES Diesel PM %ile',
  PM2_5_P: 'CES PM2.5 %ile',
  TrafficP: 'CES traffic %ile',
  AsthmaP: 'CES asthma emerg. visits %ile',
  LowBirWP: 'CES low birth weight %ile',
  CardiovasP: 'CES cardiovascular disease %ile',
  EducatP: 'CES < HS education %ile',
  Ling_IsolP: 'CES Linguistic isolation %ile',
  PovertyP: 'CES poverty %ile',
  UnemplP: 'CES unemployment %ile',
  HousBurdP: 'CES housing burden %ile',
  PopCharP: 'Population characteristics %',
  P_D2_PM25: 'EJScreen PM2.5 %ile',
  P_D2_OZONE: 'EJScreen Ozone %ile',
  P_D2_DSLPM: 'EJScreen Diesel PM %ile',
  P_D2_RSEI_AIR: 'EJScreen Toxic Releases to Air %ile',
  P_D2_PTRAF: 'EJScreen Traffic Proximity %ile',
  P_D2_NO2: 'EJScreen NO2 %ile',
  disadvantaged: 'Disadvantaged %ile',
  diesel_ex: 'CEJST diesel PM %ile',
  pm25: 'CEJST PM2.5 %ile',
  traffic: 'CEJST traffic %ile',
  low_life_ex: 'Low-life expectancy %ile',
  heart_dis: 'CEJST cardiovascular disease %ile',
  house_burd: 'CEJST Housing burden %ile',
  ling_iso: 'CEJST linguistic isolation %ile',
  education: 'CEJST < HS education %ile',
  LMI: 'Low-Moderate Income %ile',
  '100_fpl': 'Below 100% FPL',
  '200_fpl': 'Below 200% FPL',
  unemployment: 'CEJST u  nemployment %',
  non_white_pctl: 'Census nonwhite %',
  commute_pctl: 'Census commute distance %ile',
  disability_pctl: 'Census disability %',
  'Multi-Family Housing Residents': 'MFH residents',
  Renters: 'Renters',
  lev_10000: 'Registered LEVs',
  pge: 'Grid capacity (kW)',
  nevi: 'NEVI program',
  irs30c: '30c property tax credit',
}
