export const SliderConfigs = [
  // {
  //   id: 0,
  //   trigger: 'popRange',
  //   mainText: '',
  //   hoverText: '',
  //   accordionText: [''],
  //   markRange: 100,
  //   name: 'popScore',
  //   min: 0,
  //   max: 100,
  //   value: 'popScoreRange',
  // },
  {
    id: 1,
    trigger: 'toggleCiRange',
    mainText: 'CalEnviroScreen4.0 percentile',
    hoverText:
      'Slide to adjust the community environmental justice impact score. Higher scores = greater priority.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} to ${range[1]}</p>`,
      `<p>CalEnviroScreen4.0 is California’s state environmental justice impact screening tool. CES4.0 combines 21 pollution and population-based criteria into a composite score at the census tract level, with percentile rankings based on comparison to statewide averages. More information available <a href='https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-40' class='inline-link' target='blank'>here</a>.</p>`,
    ],
    markRange: 100,
    name: 'ciScore',
    min: 0,
    max: 100,
    value: 'ciScoreRange',
  },
  {
    id: 2,
    trigger: 'toggleCJESTRange',
    mainText: 'CJEST percentile',
    hoverText:
      'Slide to adjust the community environmental justice impact score. Higher scores = greater priority.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      // `<p>Range: ${range[0]}  to ${range[1] === max ? '∞' : range[1]}%</p>`,
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>CJEST (Climate and Environmental Justice Screening Tool) is a nationwide environmental justice mapping tool developed to identify disadvantaged communities based on environmental and socioeconomic indicators. CJEST evaluates multiple factors, including pollution exposure, health outcomes, and community vulnerability, to determine eligibility for federal Justice40 benefits. More information available <a href='https://www.arcgis.com/home/item.html?id=b82df3b058204ccea64619efcd8065d2' class='inline-link' target='blank'>here</a>.</p>`,
    ],
    markRange: 100,
    name: 'cjScore',
    min: 0,
    max: 100,
    value: 'cjScoreRange',
  },
  {
    id: 3,
    trigger: 'toggleCesOzoneRange',
    mainText: 'Ozone Pollution',
    hoverText: 'Ozone concentration levels, a key indicator of air quality and respiratory health risks.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate areas with worse air quality due to ozone pollution.</p>`,
    ],
    markRange: 100,
    name: 'cesOzone',
    min: 0,
    max: 100,
    value: 'cesOzoneRange',
  },
  {
    id: 4,
    trigger: 'toggleCesPm25Range',
    mainText: 'PM2.5 Pollution',
    hoverText:
      'Fine particulate matter (PM2.5) levels, linked to respiratory and cardiovascular health effects.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher concentrations indicate increased air pollution and associated health risks.</p>`,
    ],
    markRange: 100,
    name: 'cesPm25',
    min: 0,
    max: 100,
    value: 'cesPm25Range',
  },
  {
    id: 5,
    trigger: 'toggleCesDieselPmRange',
    mainText: 'Diesel PM Pollution',
    hoverText: 'Diesel particulate matter concentration, a pollutant from transportation and industry.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>This metric highlights areas with high exposure to diesel-related pollution.</p>`,
    ],
    markRange: 100,
    name: 'cesDieselPm',
    min: 0,
    max: 100,
    value: 'cesDieselPmRange',
  },
  {
    id: 6,
    trigger: 'toggleCesTrafficRange',
    mainText: 'Traffic Density',
    hoverText: 'Traffic proximity and volume, a key factor in air pollution and noise exposure.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate areas with more traffic, leading to increased pollution exposure.</p>`,
    ],
    markRange: 100,
    name: 'cesTraffic',
    min: 0,
    max: 100,
    value: 'cesTrafficRange',
  },
  {
    id: 7,
    trigger: 'toggleCesAsthmaRange',
    mainText: 'Asthma Prevalence',
    hoverText:
      'Rate of asthma-related emergency department visits, signaling air quality and environmental health concerns.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>This indicator measures the number of asthma-related hospital visits per 10,000 residents.</p>`,
    ],
    markRange: 100,
    name: 'cesAsthma',
    min: 0,
    max: 100,
    value: 'cesAsthmaRange',
  },
  {
    id: 8,
    trigger: 'toggleCesLowBirthWeightRange',
    mainText: 'Low Birth Weight',
    hoverText:
      'Percentage of infants born with low birth weight, indicating potential community health concerns.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>This metric reflects the percentage of infants born underweight.</p>`,
    ],
    markRange: 100,
    name: 'cesLowBirthWeight',
    min: 0,
    max: 100,
    value: 'cesLowBirthWeightRange',
  },
  {
    id: 9,
    trigger: 'toggleCesCardiovascularDiseaseRange',
    mainText: 'Cardiovascular Disease',
    hoverText: 'Prevalence of cardiovascular disease, linked to pollution and other environmental factors.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Environmental exposures, like air pollution, can increase cardiovascular risk.</p>`,
    ],
    markRange: 100,
    name: 'cesCardiovascularDisease',
    min: 0,
    max: 100,
    value: 'cesCardiovascularDiseaseRange',
  },
  {
    id: 10,
    trigger: 'toggleCesEducationRange',
    mainText: 'Educational Attainment',
    hoverText: 'Percentage of population over 25 without a high school diploma, a key socio-economic factor.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>This metric helps assess social vulnerability within a community.</p>`,
    ],
    markRange: 100,
    name: 'cesEducation',
    min: 0,
    max: 100,
    value: 'cesEducationRange',
  },
  {
    id: 11,
    trigger: 'toggleCesLinguisticIsolationRange',
    mainText: 'Linguistic Isolation',
    hoverText:
      'Percentage of households where no one over 14 speaks English fluently, affecting access to services.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>This measure highlights communities that may need additional support and resources.</p>`,
    ],
    markRange: 100,
    name: 'cesLinguisticIsolation',
    min: 0,
    max: 100,
    value: 'cesLinguisticIsolationRange',
  },
  {
    id: 12,
    trigger: 'toggleCesPovertyRange',
    mainText: 'Poverty Level',
    hoverText:
      'Percentage of the population living below the federal poverty line, a key economic indicator.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher poverty rates are often linked to increased environmental and health risks.</p>`,
    ],
    markRange: 100,
    name: 'cesPoverty',
    min: 0,
    max: 100,
    value: 'cesPovertyRange',
  },
  {
    id: 13,
    trigger: 'toggleCesUnemploymentRange',
    mainText: 'Unemployment Rate',
    hoverText: 'Percentage of the labor force currently unemployed, impacting economic stability.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>This metric is used to assess the economic health of a community.</p>`,
    ],
    markRange: 100,
    name: 'cesUnemployment',
    min: 0,
    max: 100,
    value: 'cesUnemploymentRange',
  },
  {
    id: 14,
    trigger: 'toggleCesHousingBurdenRange',
    mainText: 'Housing Burden',
    hoverText:
      'Percentage of income spent on housing costs, highlighting financial strain within communities.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher percentages indicate greater economic stress and potential displacement risks.</p>`,
    ],
    markRange: 100,
    name: 'cesHousingBurden',
    min: 0,
    max: 100,
    value: 'cesHousingBurdenRange',
  },
  {
    id: 15,
    trigger: 'toggleEjScreenOzoneRange',
    mainText: 'EJScreen Ozone',
    hoverText: 'Ozone pollution levels from the EPA&apos;s Environmental Justice Screening Tool.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate greater exposure to ozone pollution.</p>`,
    ],
    markRange: 100,
    name: 'ejscreenOzone',
    min: 0,
    max: 100,
    value: 'ejscreenOzoneRange',
  },
  {
    id: 16,
    trigger: 'toggleEjScreenPm25Range',
    mainText: 'EJScreen PM2.5',
    hoverText: 'Fine particulate matter (PM2.5) pollution levels from the EPA&apos;s EJScreen tool.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate increased exposure to air pollution.</p>`,
    ],
    markRange: 100,
    name: 'ejscreenPm25',
    min: 0,
    max: 100,
    value: 'ejscreenPm25Range',
  },
  {
    id: 17,
    trigger: 'toggleEjScreenDieselPmRange',
    mainText: 'EJScreen Diesel PM',
    hoverText:
      'Diesel particulate matter levels from the EPA&apos;s EJScreen tool, representing traffic-related pollution.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher concentrations indicate increased health risks due to air pollution.</p>`,
    ],
    markRange: 100,
    name: 'ejscreenDieselPm',
    min: 0,
    max: 100,
    value: 'ejscreenDieselPmRange',
  },
  {
    id: 18,
    trigger: 'toggleEjScreenRseiAirRange',
    mainText: 'EJScreen RSEI Air',
    hoverText:
      'Risk-Screening Environmental Indicators (RSEI) air emissions data from the EPA&apos;s EJScreen tool.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate areas with increased exposure to hazardous air pollutants.</p>`,
    ],
    markRange: 100,
    name: 'ejscreenRseiAir',
    min: 0,
    max: 100,
    value: 'ejscreenRseiAirRange',
  },
  {
    id: 19,
    trigger: 'toggleEjScreenPtrafRange',
    mainText: 'EJScreen Traffic Proximity',
    hoverText: 'Proximity to traffic sources, measured by the EPA&apos;s EJScreen tool.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate greater exposure to traffic-related pollution and noise.</p>`,
    ],
    markRange: 100,
    name: 'ejscreenPtraf',
    min: 0,
    max: 100,
    value: 'ejscreenPtrafRange',
  },
  {
    id: 20,
    trigger: 'toggleEjScreenNo2Range',
    mainText: 'EJScreen NO₂',
    hoverText: 'Nitrogen dioxide (NO₂) pollution levels from the EPA&apos;s EJScreen tool.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate greater exposure to NO₂ pollution, which can impact respiratory health.</p>`,
    ],
    markRange: 100,
    name: 'ejscreenNo2',
    min: 0,
    max: 100,
    value: 'ejscreenNo2Range',
  },
  {
    id: 21,
    trigger: 'toggleCjestDieselExRange',
    mainText: 'CJEST Diesel Exhaust',
    hoverText: 'Exposure to diesel exhaust emissions as measured by CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate greater exposure to diesel emissions in the area.</p>`,
    ],
    markRange: 100,
    name: 'cjestDieselEx',
    min: 0,
    max: 100,
    value: 'cjestDieselExRange',
  },
  {
    id: 22,
    trigger: 'toggleCjestPm25Range',
    mainText: 'CJEST PM2.5',
    hoverText: 'Fine particulate matter (PM2.5) pollution levels as measured by CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate greater exposure to fine particulate pollution.</p>`,
    ],
    markRange: 100,
    name: 'cjestPm25',
    min: 0,
    max: 100,
    value: 'cjestPm25Range',
  },
  {
    id: 23,
    trigger: 'toggleCjestTrafficRange',
    mainText: 'CJEST Traffic Exposure',
    hoverText: 'Traffic-related pollution exposure levels from CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate greater exposure to traffic-related pollution.</p>`,
    ],
    markRange: 100,
    name: 'cjestTraffic',
    min: 0,
    max: 100,
    value: 'cjestTrafficRange',
  },
  {
    id: 24,
    trigger: 'toggleCjestLowLifeExRange',
    mainText: 'CJEST Low Life Expectancy',
    hoverText: 'Areas with lower-than-average life expectancy as identified by CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate regions with significantly lower life expectancy.</p>`,
    ],
    markRange: 100,
    name: 'cjestLowLifeEx',
    min: 0,
    max: 100,
    value: 'cjestLowLifeExRange',
  },
  {
    id: 25,
    trigger: 'toggleCjestAsthmaRange',
    mainText: 'CJEST Asthma Rates',
    hoverText: 'Asthma prevalence levels as measured by CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate a greater prevalence of asthma in the area.</p>`,
    ],
    markRange: 100,
    name: 'cjestAsthma',
    min: 0,
    max: 100,
    value: 'cjestAsthmaRange',
  },
  {
    id: 26,
    trigger: 'toggleCjestHeartDisRange',
    mainText: 'CJEST Heart Disease',
    hoverText: 'Heart disease prevalence levels from CJEST data.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate a greater prevalence of heart disease in the area.</p>`,
    ],
    markRange: 100,
    name: 'cjestHeartDis',
    min: 0,
    max: 100,
    value: 'cjestHeartDisRange',
  },
  {
    id: 27,
    trigger: 'toggleCjestHouseBurdRange',
    mainText: 'CJEST Housing Burden',
    hoverText: 'Housing burden levels as measured by CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate greater financial strain related to housing costs.</p>`,
    ],
    markRange: 100,
    name: 'cjestHouseBurd',
    min: 0,
    max: 100,
    value: 'cjestHouseBurdRange',
  },
  {
    id: 28,
    trigger: 'toggleCjestLingIsoRange',
    mainText: 'CJEST Linguistic Isolation',
    hoverText: 'Levels of linguistic isolation in communities as measured by CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate a greater proportion of non-English-speaking households.</p>`,
    ],
    markRange: 100,
    name: 'cjestLingIso',
    min: 0,
    max: 100,
    value: 'cjestLingIsoRange',
  },
  {
    id: 29,
    trigger: 'toggleCjestEducationRange',
    mainText: 'CJEST Education Levels',
    hoverText: 'Educational attainment levels as measured by CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate lower levels of educational attainment in the area.</p>`,
    ],
    markRange: 100,
    name: 'cjestEducation',
    min: 0,
    max: 100,
    value: 'cjestEducationRange',
  },
  {
    id: 30,
    trigger: 'toggleCjestLmiRange',
    mainText: 'CJEST Low-to-Moderate Income',
    hoverText: 'Income levels categorized as low-to-moderate income by CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate a greater proportion of low-to-moderate income residents.</p>`,
    ],
    markRange: 100,
    name: 'cjestLmi',
    min: 0,
    max: 100,
    value: 'cjestLmiRange',
  },
  {
    id: 31,
    trigger: 'toggleCjestFpl100Range',
    mainText: 'CJEST Below 100% FPL',
    hoverText: 'Percentage of the population living below 100% of the federal poverty level (FPL).',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate a greater percentage of people below 100% FPL.</p>`,
    ],
    markRange: 100,
    name: 'cjestFpl100',
    min: 0,
    max: 100,
    value: 'cjestFpl100Range',
  },
  {
    id: 32,
    trigger: 'toggleCjestFpl200Range',
    mainText: 'CJEST Below 200% FPL',
    hoverText: 'Percentage of the population living below 200% of the federal poverty level (FPL).',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values indicate a greater percentage of people below 200% FPL.</p>`,
    ],
    markRange: 100,
    name: 'cjestFpl200',
    min: 0,
    max: 100,
    value: 'cjestFpl200Range',
  },
  {
    id: 33,
    trigger: 'toggleCjestUnemploymentRange',
    mainText: 'CJEST Unemployment Rate',
    hoverText: 'Unemployment levels as measured by CJEST.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>Higher values suggest a larger proportion of unemployed individuals in the area.</p>`,
    ],
    markRange: 100,
    name: 'cjestUnemployment',
    min: 0,
    max: 100,
    value: 'cjestUnemploymentRange',
  },
  {
    id: 34,
    trigger: 'toggleMultiFaRange',
    mainText: 'Multifamily residents',
    hoverText:
      'Slide to adjust the number of residents in the pixel who live in multifamily buildings (i.e., apartment, condo)',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      // `<p>Range: ${range[0]} to ${range[1] === max ? '∞' : range[1]}</p>`,
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `to ${range[1]}%`}</p>`,
      `<p>Multifamily and renter resident data are estimated based on American Community Survey data for multifamily/renter percentages by census tract and population per pixel. These residents are more likely to rely on public EV charging and mobility infrastructure than are single-family home residents.</p>`,
    ],
    markRange: 100,
    name: 'multiFa',
    min: 0,
    max: 100,
    value: 'multiFaRange',
  },
  {
    id: 35,
    trigger: 'toggleRentersRange',
    mainText: 'Renters',
    hoverText: 'Slide to adjust the number of residents in the pixel who rent their home.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      // `<p>Range: ${range[0]} to ${range[1] === max ? '∞' : range[1]}</p>`,
      `<p>Range: ${range[0]} ${range[1] > 100 ? ' and above' : ` to ${range[1]}%`}</p>`,
      `<p>Multifamily and renter resident data are estimated based on American Community Survey data for multifamily/renter percentages by census tract and population per pixel. These residents are more likely to rely on public EV charging and mobility infrastructure than are single-family home residents.</p>`,
    ],
    markRange: 100,
    name: 'renters',
    min: 0,
    max: 100,
    value: 'rentersRange',
  },
  {
    id: 36,
    trigger: 'toggleWalkableRange',
    mainText: 'L2 chargers within 10 min walk',
    hoverText:
      'Slide to adjust the number of public Level 2 EV chargers within a 10 minute walk of the pixel. Lower numbers = lower charging access in the pixel.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} to ${range[1]}${range[1] === max ? '+' : ''}</p>`,
      `<p>Level 2 and DC Fast access are estimated based on <a href="https://docs.mapbox.com/api/navigation/isochrone/" class='inline-link' target='blank'>MapBox isochrones API</a> (which estimates travel times between specific locations) and <a href="https://afdc.energy.gov/fuels/electricity-locations#/find/nearest?fuel=ELEC" class='inline-link' target='blank'>US Department of Energy current charger data</a>. Walk time is used for Level 2 chargers (which typically take multiple hours to complete a charge) while drive time is used for DC Fast chargers (which typically take 30-60 minutes), reflecting their different use cases.</p>`,
    ],
    markRange: 100,
    name: 'walkable',
    min: 0,
    max: 100,
    value: 'walkableRange',
  },
  {
    id: 37,
    trigger: 'toggleDrivableRange',
    mainText: 'DCF chargers within 10 min drive',
    hoverText:
      'Slide to adjust the number of public DC Fast chargers within a 10 minute drive of the pixel. Lower numbers = lower charging access in the pixel.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} to ${range[1]}${range[1] === max ? '+' : ''}</p>`,
      `<p>Level 2 and DC Fast access are estimated based on <a href="https://docs.mapbox.com/api/navigation/isochrone/" class='inline-link' target='blank'>MapBox isochrones API</a> (which estimates travel times between specific locations) and <a href="https://afdc.energy.gov/fuels/electricity-locations#/find/nearest?fuel=ELEC" class='inline-link' target='blank'>US Department of Energy current charger data</a>. Walk time is used for Level 2 chargers (which typically take multiple hours to complete a charge) while drive time is used for DC Fast chargers (which typically take 30-60 minutes), reflecting their different use cases.</p>`,
    ],
    markRange: 100,
    name: 'drivable',
    min: 0,
    max: 100,
    value: 'drivableRange',
  },
  // {
  //   id: 38,
  //   trigger: 'toggleCommercialRange',
  //   mainText: '',
  //   hoverText: '',
  //   accordionText: [
  //     '',
  //     ''
  //   ],
  //   markRange: 100,
  //   name: 'commercial',
  //   min: 0,
  //   max: 100,
  //   value: 'commercialRange',
  // },
  // {
  //   id: 39,
  //   trigger: 'toggleResidentialRange',
  //   mainText: '',
  //   hoverText: '',
  //   accordionText: [
  //     '',
  //     ''
  //   ],
  //   markRange: 100,
  //   name: 'residential',
  //   min: 0,
  //   max: 100,
  //   value: 'residentialRange',
  // },
  {
    id: 40,
    trigger: 'toggleLevRange',
    mainText: 'Registered LEVs',
    hoverText:
      'Slide to adjust the density of low-emitting vehicles (EVs and hydrogen fuel-cell) registered in the ZIP code.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} to ${range[1]}${range[1] === max ? '+' : ''}</p>`,
      // `<p>Range: ${range[0]} to ${range[1] === max ? range[1]+"+" : range[1]}</p>`,
      `<p>Higher LEV registrations in an area indicate a greater need for charging today but also suggest a higher early adopter rate–thus, potentially greater access to at-home charging and lower need for equity prioritization. Registrations are calculated per 1000 residents to account for population variations across ZIP codes.</p>`,
    ],
    markRange: 1000,
    name: 'lev',
    min: 0,
    max: 1000,
    value: 'levRange',
  },
  {
    id: 41,
    trigger: 'togglePgeRange',
    mainText: 'Electric grid load capacity (kW)',
    hoverText:
      'Slide to adjust the available capacity on the electrical distribution grid through the pixel. Higher numbers = more capacity to install EV chargers.',
    accordionText: ({
      range,
      max,
      jurisdiction,
      utility,
    }: {
      range: number[]
      max: number
      jurisdiction?: string
      utility?: string
    }) => [
      `<p>Range: ${range[0] === range[1] ? `${range[1]}+` : `${range[0]} to ${range[1]}`}</p>`,
      // `<p>Range: ${range[0] === range[1] ? range[1] + '+' : range[0] + ' to ' + range[1]}</p>`,
      `<p>Load capacity is based on the capacity map provided by the electric utility that serves the jurisdiction, <a href="https://www.energy.gov/eere/us-atlas-electric-distribution-system-hosting-capacity-maps" class='inline-link' target='blank'>where available</a>.` +
        `${
          jurisdiction && utility ? `<b>${jurisdiction} is in ${utility} service territory.</b>` : ''
        } Energy requirements vary widely, but 100 kW of capacity is typically needed to support 5-10 Level 2 chargers or 1 DC Fast charger.</p>`,
    ],
    markRange: 3000,
    name: 'pge',
    min: 0,
    max: 3000,
    value: 'pgeRange',
  },
  {
    id: 1001,
    trigger: 'toggleNonWhiteRange',
    mainText: '% Non-White Population',
    hoverText: 'The percentile rank of the population that identifies as non-white in a given area.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>This metric identifies communities with a higher proportion of non-white residents.</p>`,
    ],
    markRange: 100,
    name: 'nonWhite',
    min: 0,
    max: 100,
    value: 'nonWhiteRange',
  },
  {
    id: 1002,
    trigger: 'toggleCommuteRange',
    mainText: 'Commute Burden',
    hoverText: 'The percentile rank of people with long or difficult commutes in the area.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>This metric highlights areas where residents face significant commuting challenges.</p>`,
    ],
    markRange: 100,
    name: 'commute',
    min: 0,
    max: 100,
    value: 'commuteRange',
  },
  {
    id: 1003,
    trigger: 'toggleDisabilityRange',
    mainText: '% with Disability',
    hoverText: 'The percentile rank of people with disabilities in the area.',
    accordionText: ({ range, max }: { range: number[]; max: number }) => [
      `<p>Range: ${range[0]} ${range[1] > 100 ? '+' : `- ${range[1]}%`}</p>`,
      `<p>This metric highlights communities with a high percentage of individuals with disabilities.</p>`,
    ],
    markRange: 100,
    name: 'disability',
    min: 0,
    max: 100,
    value: 'disabilityRange',
  },
]
